import React from 'react';
import { X, Download } from 'lucide-react';

export default function ExportModal({
  isOpen,
  onClose,
  timeEntries,
  tasks,
  vehicles,
  maintenanceRecords,
  userRole
}) {
  if (!isOpen) return null;

  const generateReport = () => {
    const today = new Date().toLocaleDateString();
    let report = `CAR LOT DAILY REPORT - ${today}\n`;
    report += `Generated by: ${userRole === 'employee' ? 'Dan' : 'Boss'}\n`;
    report += `\n${'='.repeat(50)}\n`;

    report += `\nTIME LOG (${timeEntries.length} entries)\n`;
    report += `${'-'.repeat(50)}\n`;
    timeEntries.forEach(entry => {
      report += `${entry.time} | ${entry.duration} | ${entry.activity}\n`;
    });

    report += `\n\nTASKS (${tasks.filter(t => !t.completed).length} pending, ${tasks.filter(t => t.completed).length} completed)\n`;
    report += `${'-'.repeat(50)}\n`;
    tasks.forEach(task => {
      const status = task.completed ? '✓' : '○';
      report += `${status} [${task.priority.toUpperCase()}] ${task.task}\n`;
    });

    report += `\n\nVEHICLE STATUS\n`;
    report += `${'-'.repeat(50)}\n`;
    vehicles.forEach(v => {
      report += `${v.stock} - ${v.year} ${v.make} ${v.model} - ${v.status} - ${v.price}\n`;
    });

    report += `\n\nMAINTENANCE RECORDS\n`;
    report += `${'-'.repeat(50)}\n`;
    maintenanceRecords.forEach(r => {
      report += `${r.date} | ${r.vehicle} | ${r.service} - ${r.status}\n`;
      if (r.notes) report += `  Notes: ${r.notes}\n`;
    });

    return report;
  };

  const handleExport = () => {
    const report = generateReport();
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `carlot-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    onClose();
  };

  const handlePrint = () => {
    const report = generateReport();
    const printWindow = window.open('', '', 'height=600,width=800');
    printWindow.document.write('<html><head><title>Car Lot Report</title>');
    printWindow.document.write('<style>body{font-family:monospace;padding:20px;} h1{color:#1e40af;}</style>');
    printWindow.document.write('</head><body>');
    printWindow.document.write('<pre>' + report + '</pre>');
    printWindow.document.write('</body></html>');
    printWindow.document.close();
    printWindow.print();
    onClose();
  };

  return (
    <div className="modal-overlay fixed inset-0 bg-black

